"""add cover_jobs table

Revision ID: 77a349a83b71
Revises: d9300d11208e
Create Date: 2026-06-21 11:54:46.991242

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '77a349a83b71'
down_revision: str | Sequence[str] | None = 'd9300d11208e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('cover_path', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('result_cover_url', sa.String(), nullable=True),
    sa.Column('result_thumb_url', sa.String(), nullable=True),
    sa.Column('result_med_url', sa.String(), nullable=True),
    sa.Column('original_width', sa.Integer(), nullable=True),
    sa.Column('original_height', sa.Integer(), nullable=True),
    sa.Column('webp_bytes_saved', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('callback_delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_jobs_album_id'), 'cover_jobs', ['album_id'], unique=False)
    op.create_index(op.f('ix_cover_jobs_idempotency_key'), 'cover_jobs', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cover_jobs_idempotency_key'), table_name='cover_jobs')
    op.drop_index(op.f('ix_cover_jobs_album_id'), table_name='cover_jobs')
    op.drop_table('cover_jobs')
    # ### end Alembic commands ###
