"""add lyrics_jobs table

Revision ID: d9300d11208e
Revises: 
Create Date: 2026-06-21 09:18:10.988923

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9300d11208e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyrics_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('audio_file_path', sa.String(), nullable=True),
    sa.Column('audio_download_url', sa.String(), nullable=True),
    sa.Column('track_title', sa.String(), nullable=True),
    sa.Column('track_artist', sa.String(), nullable=True),
    sa.Column('result_lrc_content', sa.Text(), nullable=True),
    sa.Column('result_plain_text', sa.Text(), nullable=True),
    sa.Column('result_confidence', sa.Float(), nullable=True),
    sa.Column('result_detected_language', sa.String(), nullable=True),
    sa.Column('result_segment_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('callback_delivered', sa.Boolean(), nullable=False),
    sa.Column('whisper_model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_lyrics_jobs_idempotency_key'),
        'lyrics_jobs',
        ['idempotency_key'],
        unique=True,
    )
    op.create_index(op.f('ix_lyrics_jobs_track_id'), 'lyrics_jobs', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lyrics_jobs_track_id'), table_name='lyrics_jobs')
    op.drop_index(op.f('ix_lyrics_jobs_idempotency_key'), table_name='lyrics_jobs')
    op.drop_table('lyrics_jobs')
    # ### end Alembic commands ###
