import type { RouteRecordRaw } from 'vue-router'
import LayoutMusicApp from '@/layouts/LayoutMusicApp.vue'

export const appRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    component: LayoutMusicApp,
    children: [
      {
        path: '',
        name: 'app.home',
        component: () => import(/* webpackChunkName: "app-home" */ '@/pages/app/PageHome.vue'),
        meta: { title: 'Home' },
      },
      {
        path: 'search',
        name: 'search',
        component: () => import(/* webpackChunkName: "app-search" */ '@/pages/app/PageSearch.vue'),
        meta: { title: 'Search' },
      },
      {
        path: 'discover',
        redirect: '/search',
      },
      {
        path: 'recommendations',
        name: 'recommendations',
        component: () => import(/* webpackChunkName: "app-recommendations" */ '@/pages/app/recommendations/PageRecommendationsHub.vue'),
        meta: { title: 'Recommendations' },
      },
      {
        path: 'recommendations/for-you',
        name: 'recommendations.for-you',
        component: () => import(/* webpackChunkName: "app-recommendations-for-you" */ '@/pages/app/recommendations/PageRecommendationsForYou.vue'),
        meta: { title: 'For You' },
      },
      {
        path: 'recommendations/popular',
        name: 'recommendations.popular',
        component: () => import(/* webpackChunkName: "app-recommendations-popular" */ '@/pages/app/recommendations/PageRecommendationsPopular.vue'),
        meta: { title: 'Popular' },
      },
      {
        path: 'recommendations/best',
        name: 'recommendations.best',
        component: () => import(/* webpackChunkName: "app-recommendations-best" */ '@/pages/app/recommendations/PageRecommendationsBest.vue'),
        meta: { title: 'Best' },
      },
      {
        path: 'recommendations/recent',
        name: 'recommendations.recent',
        component: () => import(/* webpackChunkName: "app-recommendations-recent" */ '@/pages/app/recommendations/PageRecommendationsRecent.vue'),
        meta: { title: 'Recent' },
      },
      {
        path: 'library',
        name: 'library',
        component: () => import(/* webpackChunkName: "app-library" */ '@/pages/app/PageLibrary.vue'),
        meta: { title: 'Library', requiresAuth: true },
      },
      {
        path: 'playlists',
        redirect: '/library',
      },
      {
        path: 'playlist/:id',
        name: 'playlist.detail',
        component: () => import(/* webpackChunkName: "app-playlist-detail" */ '@/pages/app/PagePlaylistDetail.vue'),
        meta: { title: 'Playlist' },
      },
      {
        path: 'recently-played',
        redirect: '/library',
      },
      {
        path: 'track/:id',
        name: 'track.detail',
        component: () => import(/* webpackChunkName: "app-track-detail" */ '@/pages/app/PageTrack.vue'),
        meta: { title: 'Track' },
      },
      {
        path: 'album/:id',
        name: 'album.detail',
        component: () => import(/* webpackChunkName: "app-album-detail" */ '@/pages/app/PageAlbum.vue'),
        meta: { title: 'Album' },
      },
      {
        path: 'artist/:id',
        name: 'artist.detail',
        component: () => import(/* webpackChunkName: "app-artist-detail" */ '@/pages/app/PageArtist.vue'),
        meta: { title: 'Artist' },
      },
      {
        path: 'explore',
        name: 'app.explore',
        component: () => import(/* webpackChunkName: "app-explore" */ '@/pages/app/PageExplore.vue'),
        meta: { title: 'Explore' },
      },
      {
        path: 'create-edit',
        name: 'app.create-edit',
        component: () => import(/* webpackChunkName: "app-create-edit" */ '@/pages/app/PageCreateEdit.vue'),
        meta: { title: 'Create Edit', requiresAuth: true },
      },
      {
        path: 'notifications',
        name: 'notifications',
        component: () => import(/* webpackChunkName: "app-notifications" */ '@/pages/app/PageNotifications.vue'),
        meta: { title: 'Notifications', requiresAuth: true },
      },
      {
        path: 'social',
        name: 'social',
        component: () => import(/* webpackChunkName: "app-social" */ '@/pages/app/PageSocial.vue'),
        meta: { title: 'Social Hub', requiresAuth: true },
      },
      {
        path: 'social/parties/:id',
        alias: 'social/party/:id',
        name: 'social.party',
        component: () => import(/* webpackChunkName: "app-party-detail" */ '@/pages/app/PagePartyDetail.vue'),
        meta: { title: 'Listening Party' },
      },
      {
        path: 'social/rooms/:id',
        alias: 'social/room/:id',
        name: 'social.room',
        component: () => import(/* webpackChunkName: "app-room-live" */ '@/pages/app/PageRoomLive.vue'),
        meta: { title: 'Live Room' },
      },
      {
        path: 'social/clubs/browse',
        name: 'social.clubs.browse',
        component: () => import(/* webpackChunkName: "app-clubs-browse" */ '@/pages/app/PageClubsBrowse.vue'),
        meta: { title: 'Browse Clubs', requiresAuth: true },
      },
      {
        path: 'social/clubs/:id',
        alias: 'social/club/:id',
        name: 'social.club',
        component: () => import(/* webpackChunkName: "app-club-detail" */ '@/pages/app/PageClubDetail.vue'),
        meta: { title: 'Music Club' },
      },
      {
        path: 'profile',
        redirect: { name: 'user.profile' },
      },
      {
        path: 'user/:id?',
        name: 'user.profile',
        component: () => import(/* webpackChunkName: "app-user-profile" */ '@/pages/app/PageUserProfile.vue'),
        meta: { title: 'Profile' },
      },
      {
        path: 'settings',
        name: 'settings',
        component: () => import(/* webpackChunkName: "app-settings" */ '@/pages/app/PageUserSettings.vue'),
        meta: { title: 'Settings', requiresAuth: true },
      },
      {
        path: 'subscription',
        name: 'subscription',
        component: () => import(/* webpackChunkName: "app-subscription" */ '@/pages/app/PageSubscriptions.vue'),
        meta: { title: 'Subscription', requiresAuth: true },
      },
      {
        path: 'contributions',
        name: 'contributions',
        component: () => import(/* webpackChunkName: "app-contributions" */ '@/pages/app/PageContributions.vue'),
        meta: { title: 'Contributions', requiresAuth: true },
      },
      {
        path: 'creator-dashboard',
        name: 'creator.dashboard',
        component: () => import(/* webpackChunkName: "app-creator-dashboard" */ '@/pages/app/PageCreatorDashboard.vue'),
        meta: { title: 'Creator Dashboard', requiresAuth: true },
      },
      {
        path: 'upload',
        name: 'app.upload',
        component: () => import(/* webpackChunkName: "app-upload" */ '@/pages/app/PageUpload.vue'),
        meta: { title: 'Upload', requiresAuth: true, requiresPermission: 'upload_track' },
      },
      {
        path: 'upload/review',
        name: 'app.upload-review',
        component: () => import(/* webpackChunkName: "app-upload-review" */ '@/pages/app/PageUploadReview.vue'),
        meta: { title: 'Upload Review', requiresAuth: true, requiresPermission: 'review_uploads' },
      },
      {
        path: 'gamification',
        name: 'gamification',
        component: () => import(/* webpackChunkName: "app-gamification" */ '@/pages/app/PageGamification.vue'),
        meta: { title: 'Gamification', requiresAuth: true },
      },
      {
        path: 'stats',
        name: 'listening-stats',
        component: () => import(/* webpackChunkName: "app-listening-stats" */ '@/pages/app/PageListeningStats.vue'),
        meta: { title: 'Listening Stats', requiresAuth: true },
      },
      {
        path: 'ai/mood-explorer',
        name: 'ai.mood-explorer',
        component: () => import(/* webpackChunkName: "app-mood-explorer" */ '@/pages/app/PageAIMoodExplorer.vue'),
        meta: { title: 'Mood Explorer' },
      },
      {
        path: 'ai/playlist-generator',
        name: 'ai.playlist-generator',
        component: () => import(/* webpackChunkName: "app-playlist-generator" */ '@/pages/app/PageAIPlaylistGenerator.vue'),
        meta: { title: 'AI Playlist Generator', requiresAuth: true },
      },
      {
        path: 'videos',
        name: 'app.videos',
        component: () => import(/* webpackChunkName: "app-music-videos" */ '@/pages/app/PageMusicVideos.vue'),
        meta: { title: 'Music Videos' },
      },
      {
        path: 'music-video/:videoId',
        name: 'app.music-video',
        component: () => import(/* webpackChunkName: "app-music-video" */ '@/pages/app/PageMusicVideo.vue'),
        meta: { title: 'Music Video' },
      },
    ],
  },
]
